server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alarmdb?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ssafy
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    com.project.awesomegroup : info