server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://db-rds-agagroup-database.czm6m4wy4gps.ap-northeast-2.rds.amazonaws.com:3306/alarmdb?serverTimezone=Asia/Seoul&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: agaproject
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

resources:
  location: C:\Users\dhdud\OneDrive\바탕 화면\aga_project\AGA_BackEnd\awesomeGroup\src\storage\init

weatherApi:
  serviceKey: =yzFMWBLs7AYWuTK9eJVPzgpVDiu%2B04iismWehJX8qSSYubcAcVCApQs1bGE8DvCK9XBxuvdz%2F5OkUTXnQ9LoGQ%3D%3D

geoApi:
  serviceKey: AIzaSyBDcKFWOMbQxU7fJFeQA4x-QdypNNwoC2c

logging:
  level:
    com.project.awesomegroup : info